spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: postgres
    password: skillbox
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true
